openapi: 3.0.3
info:
  title: OpenApi Registration
  description: OpenApi registration specification
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /api/v1/appointment:
    post:
      tags:
        - Appointment
      operationId: createAppontment
      description: Создание записи
      requestBody:
        content:
          application/json:
            schema:
